[package]
name = "RustMQ"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"]}
tower = "0.5.2"
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
serde = {version = "1.0.228", features = ["derive"]}